use_frameworks!

target "TestSwiftyDropbox_iOS" do
    platform :ios, '9.0'
    pod 'SwiftyDropbox', :path => '../'
    pod 'MBProgressHUD', '~> 1.1.0'
end

target "TestSwiftyDropbox_macOS" do
    platform :osx, '10.11'
    pod 'SwiftyDropbox', :path => '../'
end
